import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {mkdir,mkdtemp} from 'node:fs/promises';
import path from 'node:path';
const root=process.cwd(),base='http://localhost:3102';
await mkdir(path.join(root,'data'),{recursive:true});
const testData=await mkdtemp(path.join(root,'data','integration-'));
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--webpack','--hostname','127.0.0.1','--port','3102'],{cwd:root,windowsHide:true,env:{...process.env,NODE_ENV:'development',FEB_TEST_RUN:'1',DATABASE_URL:'',DATA_DIR:testData,APP_URL:base,EMAIL_WEBHOOK_URL:'',EMAIL_WEBHOOK_TOKEN:'',DISABLE_DEMO:'false',STORAGE_DRIVER:'local',ADMIN_EMAIL:'',ADMIN_PASSWORD:''},stdio:['ignore','pipe','pipe']});
function shutdown(){if(server.exitCode!==null)return;try{if(process.platform==='win32')execFileSync('taskkill',['/PID',String(server.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});else server.kill('SIGTERM');}catch{/* Server may have already stopped. */}}
let logs='';server.stdout.on('data',b=>{logs+=b;});server.stderr.on('data',b=>{logs+=b;});let passed=0;
const ok=label=>{passed++;console.log(`PASS ${passed}: ${label}`);};
function client(){return {cookie:''};}
async function call(c,url,method='GET',value,expected=200,extra={}){const headers={Origin:base,...extra};if(c?.cookie)headers.Cookie=c.cookie;if(value&&!(value instanceof FormData))headers['Content-Type']='application/json';const r=await fetch(base+url,{method,headers,body:value instanceof FormData?value:value?JSON.stringify(value):undefined,signal:AbortSignal.timeout(60000)});const set=r.headers.getSetCookie();if(c&&set.length)c.cookie=set.map(s=>s.split(';')[0]).join('; ');const content=r.headers.get('content-type')||'';const b=content.includes('json')?await r.json():await r.text();assert.equal(r.status,expected,`${method} ${url}: ${JSON.stringify(b).slice(0,250)}`);return b;}
try{
 let ready=false;for(let i=0;i<90;i++){try{const r=await fetch(base+'/api/bootstrap',{signal:AbortSignal.timeout(1500)});if(r.ok){ready=true;break;}}catch{}if(server.exitCode!==null)throw Error('Server exited: '+logs.slice(-2500));await new Promise(r=>setTimeout(r,1000));}assert.ok(ready,'Integration server starts');
 const visitor=client(),student=client(),triage=client(),unit=client(),specialist=client(),leader=client(),admin=client();
 for(const [c,role] of [[student,'student'],[triage,'triage'],[unit,'unit'],[specialist,'specialist'],[leader,'leader'],[admin,'admin']])await call(c,'/api/auth/demo','POST',{role});
 ok('All six development roles can sign in');
 await call(visitor,'/api/tickets','GET',null,401);await call(student,'/api/admin','GET',null,403);await call(visitor,'/api/auth/demo','POST',{role:'student'},403,{Origin:'https://foreign.example'});ok('Unauthenticated, wrong-role and cross-origin access are denied');
 const categories=await call(visitor,'/api/bootstrap');assert.equal(categories.categories.length,12);assert.equal((await call(leader,'/api/tickets')).tickets.length,0);ok('Twelve categories and aggregate-only leadership');
 const created=await call(student,'/api/tickets','POST',{title:'Integration: jadwal mata kuliah',description:'Data pengujian otomatis. Jadwal mata kuliah perlu ditinjau oleh petugas akademik.',category_id:'akademik',consent:true,confidential:true},201);const id=created.ticket.id,key=created.accessCode;assert.match(created.ticket.number,/^FEB-\d{4}-\d{6,}$/);assert.ok(key);assert.ok(!('access_hash' in created.ticket));ok('Persisted ticket, unique number and one-time access code');
 await call(visitor,`/api/tickets/${id}`,'GET',null,404);await call(visitor,`/api/tickets/${id}`,'GET',null,404,{'x-tracking-key':'invalid'});await call(visitor,`/api/tickets/${id}`,'GET',null,200,{'x-tracking-key':key});await call(leader,`/api/tickets/${id}`,'GET',null,404);await call(unit,`/api/tickets/${id}`,'GET',null,404);ok('Tracking requires secret; leaders and unassigned units cannot read details');
 let detail=await call(triage,`/api/tickets/${id}`);assert.equal(detail.ticket.reporter_name,'Identitas dirahasiakan');assert.equal(detail.ticket.reporter_id,null);ok('Confidential reporter identity redacted for triage');
 const pdf=new FormData();pdf.append('file',new Blob(['%PDF-1.7\nFEB CARE TEST\n%%EOF'],{type:'application/pdf'}),'qa.pdf');const file=await call(student,`/api/tickets/${id}/attachments`,'POST',pdf,201);await call(visitor,`/api/attachments/${file.id}`,'GET',null,404);const bytes=await call(student,`/api/attachments/${file.id}`);assert.ok(bytes.startsWith('%PDF-'));const fake=new FormData();fake.append('file',new Blob(['MZ not a PDF']),'fake.pdf');await call(student,`/api/tickets/${id}/attachments`,'POST',fake,400);ok('Private attachment upload/download and file-signature rejection');
 await call(triage,`/api/tickets/${id}/messages`,'POST',{message:'Catatan INTERNAL QA',internal:true});assert.ok(!(await call(student,`/api/tickets/${id}`)).events.some(e=>e.body.includes('INTERNAL QA')));ok('Internal notes invisible to reporter');
 await call(triage,`/api/tickets/${id}`,'PATCH',{status:'resolved',reason:'Tidak boleh langsung selesai',version:detail.ticket.version},403);
 await call(triage,`/api/tickets/${id}`,'PATCH',{status:'verified',reason:'Kronologi telah diverifikasi.',version:detail.ticket.version});
 await call(triage,`/api/tickets/${id}`,'PATCH',{status:'assigned',reason:'Versi lama harus ditolak',version:detail.ticket.version,unit_id:'akademik'},409);
 detail=await call(triage,`/api/tickets/${id}`);await call(triage,`/api/tickets/${id}`,'PATCH',{status:'assigned',reason:'Diteruskan ke Layanan Akademik.',version:detail.ticket.version,unit_id:'akademik'});ok('Valid verification/assignment and stale-edit protection');
 for(const status of ['in_progress','awaiting_confirmation']){detail=await call(unit,`/api/tickets/${id}`);await call(unit,`/api/tickets/${id}`,'PATCH',{status,reason:'Jadwal telah diperiksa, hasil disampaikan.',version:detail.ticket.version});}
 detail=await call(student,`/api/tickets/${id}`);await call(student,`/api/tickets/${id}`,'PATCH',{status:'resolved',reason:'Hasil sesuai, terima kasih atas bantuannya.',version:detail.ticket.version});await call(student,`/api/tickets/${id}/rating`,'POST',{rating:5,feedback:'Alur pengujian berhasil.'});assert.equal((await call(student,`/api/tickets/${id}`)).ticket.rating,5);await call(student,`/api/tickets/${id}/messages`,'POST',{message:'Closed ticket'},400);ok('End-to-end handling, reporter confirmation, rating, closed-ticket guard');
 const secretTicket=await call(student,'/api/tickets','POST',{title:'Integration: laporan anonim sensitif',description:'Ini hanya data pengujian akses sensitif, bukan kejadian nyata di lingkungan kampus.',category_id:'etika',anonymous:true,consent:true},201);const sid=secretTicket.ticket.id,sk={'x-tracking-key':secretTicket.accessCode};await call(triage,`/api/tickets/${sid}`,'GET',null,404);await call(student,`/api/tickets/${sid}`,'GET',null,404);await call(specialist,`/api/tickets/${sid}`);await call(student,`/api/tickets/${sid}/messages`,'POST',{message:'Pesan anonim QA'},200,sk);ok('Anonymous sensitive report only accessible with secret or specialist role');
 const audit=await call(admin,'/api/admin/audit');const anonymousActions=audit.logs.filter(x=>x.entity_id===sid&&['ticket.created','ticket.message'].includes(x.action));assert.equal(anonymousActions.length,2);assert.ok(anonymousActions.every(x=>x.actor_id===null));ok('Logged-in anonymous submissions leave no account link in audit');
 assert.ok((await call(leader,'/api/metrics')).totals.total>=18);const csv=await call(leader,'/api/export');assert.ok(csv.includes('Laporan masuk'));assert.ok(!csv.includes('Nadia'));await call(student,'/api/export','GET',null,403);ok('Live metrics and role-restricted aggregate CSV export');
 const notices=await call(student,'/api/notifications');assert.ok(notices.notifications.some(n=>!n.read_at));await call(student,'/api/notifications','POST',{});assert.ok((await call(student,'/api/notifications')).notifications.every(n=>n.read_at));ok('Notifications and mark-as-read persist');
 await call(admin,'/api/admin/categories','PATCH',{id:'akademik',sla_hours:0,unit_id:'akademik'},400);await call(admin,'/api/admin/users','PATCH',{id:'demo-admin',active:false},400);ok('Admin validation prevents invalid SLA and self-disable');
 await call(student,'/api/auth/logout','POST',{});await call(student,'/api/tickets','GET',null,401);ok('Logout revokes session');
 console.log(`\n${passed} integration checks passed. Isolated data: ${testData}`);
 shutdown();
}catch(e){console.error(e);console.error(logs.slice(-4500));process.exitCode=1;shutdown();}
process.exit(process.exitCode||0);
