import {randomUUID} from 'node:crypto';
import type {Database} from './db.ts';
export async function runJobs(db:Database){
 const escalated=await db.tx(async tx=>{const rows=await tx.q("UPDATE tickets SET escalated=true,version=version+1 WHERE id IN (SELECT id FROM tickets WHERE due_at<now() AND escalated=false AND status NOT IN ('resolved','closed','rejected') ORDER BY due_at LIMIT 100 FOR UPDATE SKIP LOCKED) RETURNING id,number,sensitive,unit_id");for(const t of rows){await tx.q('INSERT INTO audit_logs(id,action,entity_id,detail) VALUES($1,$2,$3,$4)',[randomUUID(),'sla.escalated',t.id,'Target waktu terlewati']);await tx.q('INSERT INTO events(id,ticket_id,actor_label,kind,body,internal) VALUES($1,$2,$3,$4,$5,true)',[randomUUID(),t.id,'Sistem FEB CARE','system','Target penyelesaian terlewati. Koordinator diminta meninjau tindak lanjut.']);const recipients=await tx.q('SELECT id FROM users WHERE active=true AND (role=$1 OR (role=$2 AND unit_id=$3))',[t.sensitive?'specialist':'triage',t.sensitive?'specialist':'unit',t.unit_id]);for(const u of recipients)await tx.q('INSERT INTO notifications(id,user_id,ticket_id,title,body) VALUES($1,$2,$3,$4,$5)',[randomUUID(),u.id,t.id,'Perlu perhatian: target terlewati',`Tinjau penanganan ${t.number}.`]);}return rows.length;});
 await db.q('DELETE FROM sessions WHERE expires_at<now()');await db.q('DELETE FROM rate_limits WHERE expires_at<now()');
 const webhook=process.env.EMAIL_WEBHOOK_URL,token=process.env.EMAIL_WEBHOOK_TOKEN;if(!webhook||!token)return{escalated,sent:0,email:'not_configured'};if(new URL(webhook).protocol!=='https:')throw Error('Email webhook harus HTTPS');
 const tasks=await db.tx(tx=>tx.q("UPDATE outbox SET status='processing',attempts=attempts+1,next_attempt_at=now()+interval '5 minutes' WHERE id IN (SELECT id FROM outbox WHERE (status='pending' OR status='processing') AND next_attempt_at<=now() AND attempts<5 ORDER BY created_at LIMIT 20 FOR UPDATE SKIP LOCKED) RETURNING *"));let sent=0;
 for(const task of tasks){const [user]=await db.q('SELECT email,active FROM users WHERE id=$1',[task.user_id]);if(!user?.active){await db.q("UPDATE outbox SET status='failed',last_error='User inactive' WHERE id=$1",[task.id]);continue;}try{const r=await fetch(webhook,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','Idempotency-Key':task.id},body:JSON.stringify({to:user.email,subject:task.subject,text:task.body,idempotencyKey:task.id}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`HTTP ${r.status}`);await db.q("UPDATE outbox SET status='sent',last_error=NULL WHERE id=$1 AND attempts=$2",[task.id,task.attempts]);sent++;}catch(e){await db.q("UPDATE outbox SET status=$1,last_error=$2,next_attempt_at=$3 WHERE id=$4 AND attempts=$5",[task.attempts>=5?'failed':'pending',(e as Error).message.slice(0,200),new Date(Date.now()+Math.pow(2,task.attempts)*60000),task.id,task.attempts]);}}
 return{escalated,sent,email:'configured'};
}
