import {mkdir,readFile,writeFile,unlink} from 'node:fs/promises';
import path from 'node:path';
import {createHmac,createHash} from 'node:crypto';
const localDir=()=>path.join(path.resolve(process.env.DATA_DIR||'./data'),'uploads');
function safeKey(key:string){if(!/^[a-f0-9-]{36}\.(png|jpg|webp|pdf)$/.test(key))throw Error('Invalid storage key');return key;}
const hash=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
const hmac=(key:Buffer|string,value:string)=>createHmac('sha256',key).update(value).digest();
async function s3Request(method:string,key:string,bytes?:Buffer){const {S3_ENDPOINT,S3_BUCKET,S3_ACCESS_KEY_ID,S3_SECRET_ACCESS_KEY}=process.env;if(!S3_ENDPOINT||!S3_BUCKET||!S3_ACCESS_KEY_ID||!S3_SECRET_ACCESS_KEY)throw Error('Konfigurasi S3 belum lengkap');const region=process.env.S3_REGION||'auto';const url=new URL(`${S3_ENDPOINT.replace(/\/$/,'')}/${encodeURIComponent(S3_BUCKET)}/${encodeURIComponent(safeKey(key))}`);if(url.protocol!=='https:')throw Error('S3 endpoint harus HTTPS');const timestamp=new Date().toISOString().replace(/[:-]|\.\d{3}/g,''),date=timestamp.slice(0,8),payload=hash(bytes||''),headers=`host:${url.host}\nx-amz-content-sha256:${payload}\nx-amz-date:${timestamp}\n`,signed='host;x-amz-content-sha256;x-amz-date';const canonical=[method,url.pathname,'',headers,signed,payload].join('\n');const scope=`${date}/${region}/s3/aws4_request`;const toSign=`AWS4-HMAC-SHA256\n${timestamp}\n${scope}\n${hash(canonical)}`;const k=hmac(hmac(hmac(hmac(`AWS4${S3_SECRET_ACCESS_KEY}`,date),region),'s3'),'aws4_request');const signature=createHmac('sha256',k).update(toSign).digest('hex');const response=await fetch(url,{method,headers:{'x-amz-date':timestamp,'x-amz-content-sha256':payload,Authorization:`AWS4-HMAC-SHA256 Credential=${S3_ACCESS_KEY_ID}/${scope}, SignedHeaders=${signed}, Signature=${signature}`},body:bytes?new Uint8Array(bytes):undefined,signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error(`Penyimpanan S3 gagal (${response.status})`);return response;}
export async function storeFile(key:string,bytes:Buffer){safeKey(key);if(process.env.STORAGE_DRIVER==='s3'){await s3Request('PUT',key,bytes);return;}await mkdir(localDir(),{recursive:true});await writeFile(path.join(localDir(),key),bytes,{flag:'wx',mode:0o600});}
export async function loadFile(key:string){safeKey(key);if(process.env.STORAGE_DRIVER==='s3')return new Uint8Array(await(await s3Request('GET',key)).arrayBuffer());return new Uint8Array(await readFile(path.join(localDir(),key)));}
export async function removeOrphanFile(key:string){safeKey(key);if(process.env.STORAGE_DRIVER==='s3'){await s3Request('DELETE',key);return;}await unlink(path.join(localDir(),key));}
