'use client';
import {Suspense,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Header,Footer} from '@/components/public';
import {Icon} from '@/components/icon';
import {api,ErrorMessage,Loading} from '@/components/client';
import {TicketDetail} from '@/components/ticket-detail';
function Tracker(){const params=useSearchParams();const [number,setNumber]=useState(params.get('nomor')||''),[key,setKey]=useState(''),[activeKey,setActiveKey]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function load(){setError('');setBusy(true);try{const result=await api(`/api/tickets/${encodeURIComponent(number.trim())}`,{headers:{'x-tracking-key':key.trim()}});setData(result);setActiveKey(key.trim());}catch(e){setError((e as Error).message);setData(null);}finally{setBusy(false);}}async function reload(){try{setData(await api(`/api/tickets/${data.ticket.id}`,{headers:{'x-tracking-key':activeKey}}));}catch(e){setError((e as Error).message);}}return <>{!data?<div className="tracking-wrap"><span className="tracking-emblem"><Icon name="search" size={31}/></span><span className="eyebrow">[ SETIAP LANGKAH TERLIHAT ]</span><h1>Bagaimana kabar<br/><span className="blue-text">laporanmu?</span></h1><p>Masukkan nomor tiket dan kode akses rahasia.<br/>Perjalanan suaramu ada di sini.</p><form className="tracking-form stack-form" onSubmit={e=>{e.preventDefault();load();}}><label>Nomor tiket<input required value={number} onChange={e=>setNumber(e.target.value)} placeholder="FEB-2026-000001" maxLength={40}/></label><label>Kode akses rahasia<input required value={key} type="password" onChange={e=>setKey(e.target.value)} placeholder="Kode yang diterima saat mengirim laporan" maxLength={80}/></label><ErrorMessage message={error}/><button className="button primary full" disabled={busy}>{busy?'Mencari laporan…':'Lihat perkembangan'}<Icon name="arrow"/></button><div className="tracking-footnote"><Icon name="lock" size={14}/> Hanya kamu dan petugas berwenang.</div></form></div>:<div className="tracking-detail"><button className="button ghost" onClick={()=>setData(null)}><Icon name="arrow" className="rotate-back" size={16}/> Lacak laporan lain</button><ErrorMessage message={error}/><TicketDetail data={data} reload={reload} accessKey={activeKey}/></div>}</>;}
export default function TrackPage(){return <><Header/><main className="public-workspace"><Suspense fallback={<Loading/>}><Tracker/></Suspense></main><Footer/></>;}
