import {randomUUID} from 'node:crypto';
import {getDb,type Database,type Row} from './db.ts';
import {digest,AppError} from './security.ts';
import {closedStatuses,type User} from './shared.ts';
export function scope(user:User,offset=1):{where:string;params:any[]}{if(user.role==='student')return {where:`t.reporter_id=$${offset}`,params:[user.id]};if(user.role==='triage')return {where:'t.sensitive=false',params:[]};if(user.role==='specialist')return {where:'t.sensitive=true',params:[]};if(user.role==='unit')return {where:`t.sensitive=false AND t.unit_id=$${offset}`,params:[user.unit_id]};if(user.role==='admin')return {where:'true',params:[]};return {where:'false',params:[]};}
export const ticketSelect='SELECT t.*,c.name AS category_name,u.name AS unit_name,r.name AS reporter_name FROM tickets t JOIN categories c ON c.id=t.category_id LEFT JOIN units u ON u.id=t.unit_id LEFT JOIN users r ON r.id=t.reporter_id';
export async function accessTicket(id:string,user:User|null,key?:string|null,db?:Database){const conn=db||await getDb();const [ticket]=await conn.q(`${ticketSelect} WHERE t.id=$1 OR t.number=$1`,[id]);if(!ticket)throw new AppError('Laporan tidak ditemukan atau Anda tidak memiliki akses.',404);const owner=!!user&&ticket.reporter_id===user.id;const tokenOwner=!!key&&digest(key)===ticket.access_hash;const allowed=!!user&&(user.role==='admin'||user.role==='triage'&&!ticket.sensitive||user.role==='specialist'&&ticket.sensitive||user.role==='unit'&&!ticket.sensitive&&ticket.unit_id===user.unit_id);if(!owner&&!tokenOwner&&!allowed)throw new AppError('Laporan tidak ditemukan atau Anda tidak memiliki akses.',404);return {ticket,owner:owner||tokenOwner,staff:allowed&&!owner&&!tokenOwner};}
export function safeTicket(ticket:Row,user:User|null,owner=false){const {access_hash,reporter_name,reporter_id,feedback,...rest}=ticket;const admin=user?.role==='admin';return {...rest,reporter_name:owner?'Anda':admin?(reporter_id?reporter_name:'Identitas dirahasiakan'):ticket.confidential||!reporter_id?'Identitas dirahasiakan':reporter_name,reporter_id:owner||admin?reporter_id:null,feedback:owner||admin?feedback:undefined};}
export async function audit(db:Database,actor:string|null,action:string,id:string|null,detail=''){await db.q('INSERT INTO audit_logs(id,actor_id,action,entity_id,detail) VALUES($1,$2,$3,$4,$5)',[randomUUID(),actor,action,id,detail]);}
export async function notify(db:Database,userId:string|null,ticketId:string,title:string,body:string){if(!userId)return;await db.q('INSERT INTO notifications(id,user_id,ticket_id,title,body) VALUES($1,$2,$3,$4,$5)',[randomUUID(),userId,ticketId,title,body]);await db.q('INSERT INTO outbox(id,user_id,subject,body) VALUES($1,$2,$3,$4)',[randomUUID(),userId,title,'Ada pembaruan laporan FEB CARE. Masuk ke akun Anda untuk melihat detailnya.']);}
export async function event(db:Database,id:string,user:User|null,body:string,status:string|null,internal=false,owner=false){await db.q('INSERT INTO events(id,ticket_id,actor_id,actor_label,kind,body,status,internal) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[randomUUID(),id,user?.id||null,owner?'Pelapor':user?.role==='specialist'?'Tim Perlindungan':'Tim FEB CARE',status?'status':'message',body,status,internal]);}
export async function metrics(user:User,days=30){const db=await getDb();const scoped=['leader','admin'].includes(user.role)?{where:'true',params:[]}:scope(user);const params=[...scoped.params,new Date(Date.now()-days*86400000)],where=`${scoped.where} AND t.created_at>=$${params.length}`;
 const [totals]=await db.q(`SELECT count(*)::int AS total,count(*) FILTER(WHERE status='resolved')::int AS resolved,count(*) FILTER(WHERE status NOT IN ('resolved','closed','rejected'))::int AS active,count(*) FILTER(WHERE status NOT IN ('resolved','closed','rejected') AND due_at<now())::int AS overdue,count(*) FILTER(WHERE status='awaiting_confirmation')::int AS awaiting,round(avg(extract(epoch from (resolved_at-created_at))/86400) FILTER(WHERE status='resolved')::numeric,1) AS avg_days,round(avg(rating)::numeric,1) AS rating FROM tickets t WHERE ${where}`,params);
 const distribution=await db.q(`SELECT c.name,c.icon,count(*)::int AS total FROM tickets t JOIN categories c ON t.category_id=c.id WHERE ${where} GROUP BY c.name,c.icon ORDER BY total DESC`,params);
 const trend=await db.q(`SELECT to_char(t.created_at,'YYYY-MM-DD') AS day,count(*)::int AS total,count(*) FILTER(WHERE t.status='resolved')::int AS resolved FROM tickets t WHERE ${where} GROUP BY day ORDER BY day`,params);
 const units=await db.q(`SELECT coalesce(u.name,'Belum ditugaskan') AS name,count(*)::int AS total,count(*) FILTER(WHERE t.status='resolved')::int AS resolved,count(*) FILTER(WHERE t.due_at<now() AND t.status NOT IN ('resolved','closed','rejected'))::int AS overdue FROM tickets t LEFT JOIN units u ON u.id=t.unit_id WHERE ${where} GROUP BY u.name ORDER BY total DESC`,params);
 return {totals:{...totals,resolution_rate:totals.total?Math.round(totals.resolved/totals.total*100):0},distribution,trend,units,days};}
