'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useApi,Loading,ErrorMessage} from '@/components/client';
import {useSession} from '@/components/dashboard-shell';
import {TicketTable} from '@/components/ticket-table';
import {Icon} from '@/components/icon';
import {statuses} from '@/lib/shared';
export default function Reports(){const {user}=useSession();const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1),[overdue,setOverdue]=useState(false);const {data:bootstrap}=useApi('/api/bootstrap');useEffect(()=>{const id=setTimeout(()=>{setQuery(search);setPage(1);},300);return()=>clearTimeout(id);},[search]);const {data,loading,error}=useApi(`/api/tickets?${new URLSearchParams({search:query,status,category,page:String(page),overdue:String(overdue)})}`);return <><div className="page-heading"><div><span className="eyebrow">[ SETIAP SUARA PUNYA PERJALANAN ]</span><h1>{user.role==='student'?'Laporan saya.':'Ruang tindak lanjut.'}</h1><p>{user.role==='student'?'Semua cerita dan progresnya, dalam satu tempat.':'Tinjau, prioritaskan, dan tindak lanjuti laporan yang menjadi tanggung jawabmu.'}</p></div>{user.role==='student'&&<Link href="/lapor" className="button primary"><Icon name="plus" size={17}/> Buat laporan</Link>}</div><section className="panel table-panel"><div className="filters"><label className="search-input"><Icon name="search" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari judul atau nomor tiket" aria-label="Cari laporan"/></label><select aria-label="Filter status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Semua status</option>{Object.entries(statuses).map(([k,s])=><option value={k} key={k}>{s.label}</option>)}</select><select aria-label="Filter kategori" value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">Semua kategori</option>{bootstrap?.categories.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="list-meta"><span>{data?.total||0} laporan ditemukan</span><label className="check-label"><input type="checkbox" checked={overdue} onChange={e=>{setOverdue(e.target.checked);setPage(1);}}/>Melewati target SLA</label></div><ErrorMessage message={error}/>{loading?<Loading/>:<TicketTable tickets={data?.tickets||[]}/>}<div className="pagination"><span>Halaman {page} dari {data?.pages||1}</span><div><button className="icon-button" aria-label="Halaman sebelumnya" disabled={page<=1||loading} onClick={()=>setPage(page-1)}><Icon name="chevron" className="rotate-back" size={16}/></button><button className="icon-button" aria-label="Halaman berikutnya" disabled={page>=(data?.pages||1)||loading} onClick={()=>setPage(page+1)}><Icon name="chevron" size={16}/></button></div></div></section></>;}
