'use client';
import {useRef,useState} from 'react';
import {useSession} from '@/components/dashboard-shell';
import {api,useApi,ErrorMessage,Loading} from '@/components/client';
import {Icon} from '@/components/icon';
import {roles,studyPrograms} from '@/lib/shared';

function CategoryRow({category,units,reload}:{category:any;units:any[];reload:()=>Promise<void>}){
 const [hours,setHours]=useState(category.sla_hours),[unit,setUnit]=useState(category.unit_id),[active,setActive]=useState(category.active),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <tr><td>{category.name}{category.sensitive&&<span className="badge red">Terbatas</span>}</td><td><input type="number" aria-label={`SLA ${category.name}`} value={hours} min={1} max={720} onChange={e=>setHours(Number(e.target.value))}/></td><td><select aria-label={`Unit ${category.name}`} value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></td><td><input type="checkbox" aria-label={`Aktifkan ${category.name}`} checked={active} onChange={e=>setActive(e.target.checked)}/></td><td><button className="button secondary small" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/api/admin/categories',{method:'PATCH',body:JSON.stringify({id:category.id,sla_hours:hours,unit_id:unit,active})});setMessage('Tersimpan');await reload();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Simpan</button>{message&&<small className="save-feedback">{message}</small>}</td></tr>;
}

function PasswordForm({onError}:{onError:(message:string)=>void}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <form className="stack-form narrow" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');onError('');const form=e.currentTarget;try{await api('/api/auth/password',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();setMessage('Kata sandi berhasil diperbarui.');}catch(error){onError((error as Error).message);}finally{setBusy(false);}}}><label>Kata sandi saat ini<input type="password" name="current" required autoComplete="current-password"/></label><label>Kata sandi baru<input type="password" name="password" minLength={12} maxLength={128} required autoComplete="new-password"/></label><button className="button primary" disabled={busy}>{busy?'Menyimpan…':'Perbarui kata sandi'}</button>{message&&<small className="save-feedback">{message}</small>}</form>;
}

function ProfilePanel({user,onError}:{user:any;onError:(message:string)=>void}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');onError('');try{await api('/api/auth/profile',{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setMessage('Profil berhasil diperbarui.');}catch(error){onError((error as Error).message);}finally{setBusy(false);}}
 return <div className="settings-content"><h3>Edit akun</h3><p className="form-description">Perbarui informasi akun yang digunakan untuk masuk dan menerima pemberitahuan.</p><form className="stack-form narrow" onSubmit={save}>
  <label>Nama lengkap<input name="name" defaultValue={user.name} required minLength={2} maxLength={100}/></label><label>Email<input type="email" name="email" defaultValue={user.email} required/></label><label>Nomor WhatsApp <small>(opsional)</small><input name="phone" defaultValue={user.phone||''} placeholder="08xxxxxxxxxx" inputMode="tel"/></label>
  {user.role==='student'&&<><label>NIM <small>(opsional)</small><input name="student_number" defaultValue={user.student_number||''} maxLength={30}/></label><label>Program studi <small>(opsional)</small><select name="study_program" defaultValue={user.study_program||''}><option value="">Pilih program studi</option>{studyPrograms.map(program=><option key={program} value={program}>{program}</option>)}</select></label><label>Tahun angkatan <small>(opsional)</small><input type="number" name="cohort_year" defaultValue={user.cohort_year||''} min={2000} max={new Date().getFullYear()}/></label></>}
  <button className="button primary" disabled={busy}>{busy?'Menyimpan…':'Simpan perubahan'}</button>{message&&<small className="save-feedback">{message}</small>}
 </form><hr className="settings-divider"/><h3>Ubah kata sandi</h3><p className="form-description">Gunakan minimal 12 karakter. Seluruh sesi lain akan diakhiri setelah perubahan.</p><PasswordForm onError={onError}/></div>;
}

export default function Settings(){
 const {user}=useSession();const admin=user.role==='admin';const {data,loading,error,reload}=useApi<any>(admin?'/api/admin':null);const [tab,setTab]=useState(admin?'users':'account'),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<any>(null);const dialog=useRef<HTMLDialogElement>(null);
 function openCreate(){setEditing(null);setErr('');requestAnimationFrame(()=>dialog.current?.showModal());}function openEdit(account:any){setEditing(account);setErr('');requestAnimationFrame(()=>dialog.current?.showModal());}
 async function saveUser(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr('');const values:any=Object.fromEntries(new FormData(e.currentTarget));if(!values.password)delete values.password;if(editing)values.id=editing.id;try{await api('/api/admin/users',{method:editing?'PATCH':'POST',body:JSON.stringify(values)});dialog.current?.close();setEditing(null);await reload();}catch(error){setErr((error as Error).message);}finally{setBusy(false);}}
 const adminContent=data&&(tab==='users'?<div className="table-scroll"><table className="ticket-table"><thead><tr><th>Pengguna</th><th>Peran</th><th>Unit</th><th>Status</th><th>Akses</th><th>Edit</th></tr></thead><tbody>{data.users.map((account:any)=><tr key={account.id}><td><strong>{account.name}</strong><small className="table-secondary">{account.email}</small></td><td>{roles[account.role]}</td><td>{data.units.find((unit:any)=>unit.id===account.unit_id)?.name||'—'}</td><td><span className={`badge ${account.active?'green':'gray'}`}>{account.active?'Aktif':'Nonaktif'}</span></td><td><button className="button secondary small" disabled={account.id===user.id||busy} onClick={async()=>{setBusy(true);try{await api('/api/admin/users',{method:'PATCH',body:JSON.stringify({id:account.id,active:!account.active})});await reload();}catch(error){setErr((error as Error).message);}finally{setBusy(false);}}}>{account.active?'Nonaktifkan':'Aktifkan'}</button></td><td><button className="button secondary small" onClick={()=>openEdit(account)}>Edit</button></td></tr>)}</tbody></table></div>:tab==='categories'?<><div className="panel-title"><p>SLA dihitung dalam jam kalender. Perubahan berlaku untuk laporan baru.</p></div><div className="table-scroll"><table className="ticket-table settings-table"><thead><tr><th>Kategori</th><th>SLA (jam)</th><th>Unit default</th><th>Aktif</th><th>Simpan</th></tr></thead><tbody>{data.categories.map((category:any)=><CategoryRow key={category.id} category={category} units={data.units} reload={reload}/>)}</tbody></table></div></>:<div className="settings-content"><h3>Unit penanganan</h3><div className="units-grid">{data.units.map((unit:any)=><div key={unit.id}><Icon name="building" size={23}/><strong>{unit.name}</strong></div>)}</div><form className="inline-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);try{await api('/api/admin/units',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await reload();}catch(error){setErr((error as Error).message);}finally{setBusy(false);}}}><input name="name" placeholder="Nama unit baru" aria-label="Nama unit baru" required minLength={3}/><button className="button primary" disabled={busy}>Tambah unit <Icon name="plus" size={16}/></button></form></div>);
 return <><div className="page-heading"><div><span className="eyebrow">{admin?'[ FONDASI PELAYANAN ]':'[ AKUN SAYA ]'}</span><h1>{admin?'Atur ruang kerja.':'Kelola akun.'}</h1><p>{admin?'Kelola akses, unit penanganan, dan standar layanan FEB CARE.':'Perbarui profil dan keamanan akun FEB CARE kamu.'}</p></div>{admin&&tab==='users'&&<button className="button primary" onClick={openCreate}><Icon name="plus" size={17}/>Tambah pengguna</button>}</div>
 {admin&&<div className="settings-tabs" role="tablist">{[['users','Pengguna'],['categories','Kategori & SLA'],['units','Unit penanganan'],['account','Akun saya']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>{setTab(id);setErr('');}}>{label}</button>)}</div>}
 <ErrorMessage message={error||err}/>{admin&&loading&&tab!=='account'?<Loading/>:tab==='account'?<section className="panel table-panel"><ProfilePanel user={user} onError={setErr}/></section>:data&&<section className="panel table-panel">{adminContent}</section>}
 {admin&&<dialog ref={dialog} className="app-dialog"><div className="dialog-heading"><div><span className="eyebrow">{editing?'EDIT AKUN':'AKSES BARU'}</span><h2>{editing?'Ubah pengguna.':'Tambah pengguna.'}</h2></div><button className="icon-button" onClick={()=>dialog.current?.close()} aria-label="Tutup dialog"><Icon name="close"/></button></div><form key={editing?.id||'new'} onSubmit={saveUser} className="stack-form"><label>Nama lengkap<input name="name" defaultValue={editing?.name||''} required minLength={2} maxLength={100}/></label><label>Email<input type="email" name="email" defaultValue={editing?.email||''} required/></label><div className="form-two"><label>Peran<select name="role" defaultValue={editing?.role||'student'}>{Object.entries(roles).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Unit<select name="unit_id" defaultValue={editing?.unit_id||''}><option value="">Tidak ada</option>{data?.units.map((unit:any)=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label></div><label>Nomor WhatsApp <small>(opsional)</small><input name="phone" defaultValue={editing?.phone||''}/></label>{(!editing||editing.role==='student')&&<><label>NIM <small>(opsional)</small><input name="student_number" defaultValue={editing?.student_number||''}/></label><label>Program studi <small>(opsional)</small><select name="study_program" defaultValue={editing?.study_program||''}><option value="">Pilih program studi</option>{studyPrograms.map(program=><option key={program} value={program}>{program}</option>)}</select></label><label>Tahun angkatan <small>(opsional)</small><input type="number" name="cohort_year" defaultValue={editing?.cohort_year||''} min={2000} max={new Date().getFullYear()}/></label></>}<label>{editing?'Kata sandi baru':'Kata sandi awal'} <small>{editing?'(opsional)':'(wajib)'}</small><input name="password" type="password" minLength={12} maxLength={128} required={!editing} autoComplete="new-password"/><small className="field-hint">Minimal 12 karakter.</small></label><ErrorMessage message={err}/><button className="button primary full" disabled={busy}>{busy?'Menyimpan…':editing?'Simpan perubahan':'Buat pengguna'}<Icon name="plus" size={18}/></button></form></dialog>}
</>;
}
